apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: newmonitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      nodeSelector:
        monitoring: newmonitoring
      containers:
        - name: grafana
          image: grafana/grafana:8.3.3
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: admin
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: admin
          resources:
            limits:
              cpu: '2'
              memory: 1Gi
            requests:
              cpu: 1
              memory: 128Mi
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /api/health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 30
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /api/health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          volumeMounts:
            - name: data
              mountPath: /var/lib/grafana
              subPath: grafana
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: grafana-pvc

