apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-state-metrics
  namespace: newmonitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-state-metrics
  template:
    metadata:
      labels:
        app: kube-state-metrics
    spec:
      serviceAccountName: kube-state-metrics-newmonitoring
      containers:
        - name: kube-state-metrics
          image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.3.0
          ports:
            - containerPort: 8080

